version: '3.8'
services:
  streamlit:
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    container_name: streamlit_app
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./streamlit_app:/app
  backend:
    build:
      context: ./react_app/backend
    ports:
      - "8000:8000"
    container_name: fastapi_backend
    volumes:
      - ./react_app/backend:/app
  frontend:
    build:
      context: ./react_app/frontend
    ports:
      - "3000:3000"
    container_name: react_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./react_app/frontend:/app
      - /app/node_modules
